version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "rails server"
    volumes:
      - '.:/app'
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: production
